Fix bug: CNV must-gather hangs on sriov_numvfs when PCIe device is unbound
When running CNV must-gather on a node with an unbound PCIe device, the
node_gather container blocks while reading:
```
/usr/bin/cat /host/sys/bus/pci/devices/0000:3d:00.0/sriov_numvfs
```

Trying to fix this issue by running the `oc cp` commands with timeout of
one minute.

Signed-off-by: Nahshon Unna Tsameret <nahsh.ut@gmail.com>

diff --git a/collection-scripts/gather_nodes b/collection-scripts/gather_nodes
--- a/collection-scripts/gather_nodes
+++ b/collection-scripts/gather_nodes
@@ -85,8 +85,11 @@ function gather_single_pod() {
         if oc exec "$pod" -n node-gather -- [ -d "/host/$conf_dir" ] 2>/dev/null; then
             CNI_COFIG_PATH=${NODE_PATH}/$conf_dir
             mkdir -p "${CNI_COFIG_PATH}"
-            oc cp "$pod:/host/$conf_dir ${CNI_COFIG_PATH}" -n node-gather 2>/dev/null
-    fi
+            timeout 60 oc cp "$pod:/host/$conf_dir ${CNI_COFIG_PATH}" -n node-gather 2>/dev/null
+            if [[ $? == 124 ]]; then
+              echo "[ERROR] timeout copying /host/${conf_dir} from ${pod}"
+            fi
+        fi
     done
     IFS=$'\n'
 
@@ -96,10 +99,16 @@ function gather_single_pod() {
     oc exec "$pod" -n node-gather -- lspci -vv 2>/dev/null >> "${NODE_PATH}/lspci"
 
     if oc exec "$pod" -n node-gather -- [ -f /host/etc/pcidp/config.json ] 2>/dev/null; then
-        oc cp "$pod:/host/etc/pcidp/config.json" "${NODE_PATH}/pcidp_config.json" -n node-gather 2>/dev/null
+        timeout 60 oc cp "$pod:/host/etc/pcidp/config.json" "${NODE_PATH}/pcidp_config.json" -n node-gather 2>/dev/null
+        if [[ $? == 124 ]]; then
+          echo "[ERROR] timeout copying /host/etc/pcidp/config.json from ${pod}"
+        fi
     fi
     if oc exec "$pod" -n node-gather -- [ -f /host/var/log/audit/audit.log ] 2>/dev/null; then
-        oc cp "$pod:/host/var/log/audit/audit.log" "${NODE_PATH}/audit.log" -n node-gather 2>/dev/null
+        timeout 60 oc cp "$pod:/host/var/log/audit/audit.log" "${NODE_PATH}/audit.log" -n node-gather 2>/dev/null
+        if [[ $? == 124 ]]; then
+          echo "[ERROR] timeout copying /host/var/log/audit/audit.log from ${pod}"
+        fi
     fi
 }
 
